;Implement a frame system with inheritance that supports the definition
;of three kinds of slots: properties of a class that may be inherited by
;subclasses, properties that are inherited by instances of the class but not by
;subclasses, and properties of the class and its subclasses that are not
;inherited by instances (class properties). Discuss the benefits, uses, and
;problems with this distinction.