;Create a three step path predicate for the knight’s tour:
;path3(X, Y) :- move(X, Z), move(Z, W), move (W, Y).
;Create a tree that demonstrates the full search for the path3 predicate.
;Place the cut operator between the second and third move predicates.
;Show how this prunes the tree. Next place the cut between the first and
;second move predicates and again demonstrate how the tree is pruned.
;Finally, put two cuts within the path3 predicate and show how this
;prunes the search.

