;Write Prolog code to solve the full 8 X 8 knight’s tour problem. This will
;require a lot of effort if all the move(X, Y) facts on the full chessboard
;are itemized. It is much better to create a set of eight predicates that
;capture the general rules for moving the knight on the full chessboard. You
;will also have to create a new representation for the squares on the board.
;Hint: consider a predicate containing the two element order pair, for
;example, state(Row, Column).